version: '3'
services:

  boot:
    image: boot:latest
    container_name: boot1
    volumes:
      - ./logs:/logs
      - ./application.yml:/application.yml
    environment:
      - JAVA_OPTS=-Xms1024M -Xmx1024M -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:+PrintGCDetails -XX:+PrintGCTimeStamps
    network_mode: "bridge"
    ports:
      - 8080:8080
    restart: always
